#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'test_module'
require 'korekto/context_search'

# Mockup
# rubocop: disable Metrics
module Korekto
  class Error < StandardError; end

  MockUp.create(self, :Context)
  MockUp.create(self, :StatementStruct)

  class TestContextSearch
    include ContextSearch

    def initialize(context, struct)
      @context = context
      @s = struct
    end
  end
end

class TestContextSearch < Test::Unit::TestCase
  include TestModule

  def test_coverage = coverage(Korekto::ContextSearch)

  def setup
    @context = Korekto::Context.new
    @s = Korekto::StatementStruct.new
    @test = Korekto::TestContextSearch.new(@context, @s)
  end

  def test_follows_get
    output = @test.follows_get(2)
    assert_equal @context, output
    assert_equal [[:heap], [:follows, 2]], output.missing_calls
  end

  def test_detect_statement
    output = @test.detect_statement('type', 'statement')
    assert_equal output, @context
    assert_equal [[:get, @s], [:regexp], [:match?, 'statement']],
                 @context.missing_calls
    assert_equal %i[code [] to_sym], @s.missing_calls.map(&:first)
    @context.missing_calls.clear
    @s.missing_calls.clear
    def @s.code = ''
    def @context.find = yield(self)
    output = @test.detect_statement('type', 'statement')
    assert_equal output, @context
    assert_equal [[:type, 'type'], [:regexp], [:match?, 'statement']],
                 @context.missing_calls
    assert_equal [], @s.missing_calls
    @context.missing_calls.clear
    def @context.find = nil
    e = assert_raises(Korekto::Error) do
      @test.detect_statement('type', 'statement')
    end
    assert_equal "no matching 'type' pattern", e.message
    assert_equal [[:type, 'type']], @context.missing_calls
    assert_equal [], @s.missing_calls
    @context.missing_calls.clear
    # Test A2.wut capture
    def @s.code = 'T1/A2.wut'
    @test.detect_statement('type', 'statement')
    assert_equal %i[get A2.wut], @context.missing_calls.first
  end

  def test_heap_combos_search_code
    def @s.code = 'not type'
    def @s.statement = 'statement'
    def @context.to_str = 'context'
    assert_nil @test.heap_combos_search_code('type')
    def @s.code = '/type1.wut,A2,B3'
    output = @test.heap_combos_search_code('type')
    assert_equal [@context, @context, @context], output
    @context.missing_calls.clear
    @s.missing_calls.clear
    def @context.match?(_) = false
    assert_nil @test.heap_combos_search_code('type')
    assert_equal [%i[get type1.wut], %i[get A2], %i[get B3], [:regexp]],
                 @context.missing_calls
    assert_equal [], @s.missing_calls
  end

  def test_heap_combos_search_all
    assert_nil @test.heap_combos_search_all('type')
    assert_equal [[:type, 'type'], [:heap], [:combos]], @context.missing_calls
    @context.missing_calls.clear
    def @s.statement = 'statement'
    def @context.type(_) = [self]
    def @context.combos = yield('s1', 's2')
    output = @test.heap_combos_search_all('type')
    assert_equal [@context, 's1', 's2'], output
    assert_equal [[:heap], [:regexp], [:match?, "s1\ns2\nstatement"]],
                 @context.missing_calls
    assert_equal [], @s.missing_calls
  end

  def test_heap_combos_search
    def @test.heap_combos_search_code(_) = nil
    def @test.heap_combos_search_all(_) = nil
    e = assert_raises(Korekto::Error) { @test.heap_combos_search('type') }
    assert_equal "does not match any 'type' statement combos in heap", e.message
    def @test.heap_combos_search_code(_) = 'A'
    def @test.heap_combos_search_all(_) = 'B'
    assert_equal 'A', @test.heap_combos_search('type')
    def @test.heap_combos_search_code(_) = nil
    assert_equal 'B', @test.heap_combos_search('type')
  end

  def test_heap_search_code
    def @context.to_str = 'context'
    def @s.statement = 'statement'
    def @s.code = 'A3/B1.wut,C2.wut'
    assert_nil @test.heap_search_code('C')
    def @s.code = 'A2/C1.wut,B2.wut'
    output = @test.heap_search_code('C')
    assert_equal [@context, @context], output
    assert_equal [%i[get C1.wut], %i[get B2.wut], [:regexp],
                  [:match?, "context\nstatement"]], @context.missing_calls
  end

  def test_heap_search_all
    assert_nil @test.heap_search_all('type')
    @context.missing_call.clear
    def @context.type(_) = [self]
    def @context.each = yield('s1')
    def @s.statement = 'statement'
    output = @test.heap_search_all('type')
    assert_equal [@context, 's1'], output
    assert_equal [:match?, "s1\nstatement"], @context.missing_calls.last
  end

  def test_heap_search
    def @test.heap_search_code(_) = 'A'
    def @test.heap_search_all(_) = 'B'
    assert_equal 'A', @test.heap_search('E')
    def @test.heap_search_code(_) = nil
    assert_equal 'B', @test.heap_search('E')
    def @test.heap_search_all(_) = nil
    e = assert_raises(Korekto::Error) { @test.heap_search('E') }
    assert_equal "does not match any 'E' statement in heap", e.message
  end

  # Last, check rubocop and reek
  def test_rubocop_and_reek
    file = 'lib/korekto/context_search.rb'
    rubocop(file) && reek(file) && rubocop(__FILE__)
  end
end
# rubocop: enable Metrics
