#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'colorize'
require 'korekto/heap'
require_relative 'test_module'

# Mockup
module Korekto
  class Heap
    def test_limit = @limit
    def test_combos = @combos
    def test_a = @a
  end
end

# rubocop: disable Metrics
class TestHeap < Test::Unit::TestCase
  include TestModule

  def test_coverage = coverage Korekto::Heap

  def setup
    @heap = Korekto::Heap.new(3)
  end

  def test_initialize
    assert_equal 0, @heap.test_a.size
    assert_equal 3, @heap.test_limit
    assert_equal [[0, 1], [1, 0], [0, 2], [2, 0], [1, 2], [2, 1]],
                 @heap.test_combos
  end

  def test_each
    # heap starts empty
    # rubocop: disable Lint/UnreachableLoop
    assert_nothing_raised { @heap.each { raise } }
    # rubocop: enable Lint/UnreachableLoop
    # heap iterates through a
    @heap.test_a.push(1, 2, 3, 4)
    assert_equal %w[1 2 3 4], @heap.map(&:to_s)
  end

  def test_antecedent
    @heap.test_a.push(1, 2, 3, 4)
    assert_equal '1', @heap.antecedent
  end

  def test_follows
    @heap.test_a.push(1, 2, 3, 4)
    assert_equal [2, 1], @heap.follows(1)
    assert_equal [3, 2, 1], @heap.follows(2)
  end

  def test_swap
    @heap.test_a.push(1, 2, 3, 4)
    tmp = @heap.swap
    assert_equal [1, 2, 3, 4], tmp
    assert_empty @heap.test_a
    @heap.swap tmp
    assert_equal [1, 2, 3, 4], @heap.test_a
  end

  def test_combos
    a = []

    @heap.combos { |s1, s2| a << "#{s1};#{s2}" }
    assert a.empty?

    @heap.add 'A'
    @heap.combos { |s1, s2| a << "#{s1};#{s2}" }
    assert a.empty?

    @heap.add 'B'
    @heap.combos { |s1, s2| a << "#{s1};#{s2}" }
    assert_equal 2, a.length
    assert_equal 'B;A', a[0]
    assert_equal 'A;B', a[1]

    a.clear
    @heap.add 'C'
    @heap.combos { |s1, s2| a << "#{s1};#{s2}" }
    assert_equal 6, a.length
    assert_equal 'C;B', a[0]
    assert_equal 'B;C', a[1]
    assert_equal 'C;A', a[2]
    assert_equal 'A;C', a[3]
    assert_equal 'B;A', a[4]
    assert_equal 'A;B', a[5]

    a.clear
    @heap.add 'D'
    @heap.combos { |s1, s2| a << "#{s1};#{s2}" }
    assert_equal 6, a.length
    # Note that with a heap of 3, "A" is gone.
    assert_equal 'D;C', a[0]
    assert_equal 'C;D', a[1]
    assert_equal 'D;B', a[2]
    assert_equal 'B;D', a[3]
    assert_equal 'C;B', a[4]
    assert_equal 'B;C', a[5]
  end

  def test_combos4
    a = []
    heap = Korekto::Heap.new(4)
    %w[A B C D].each { heap.add it }
    heap.combos { |x, y| a << "#{x};#{y}" }
    assert_equal 12, a.length
    assert_equal a, a.uniq
    assert_equal 'D;C', a.first
    assert_equal 'A;B', a.last
  end

  def test_combos13
    a = []
    heap = Korekto::Heap.new(13)
    %w[1 2 3 4 5 6 7 8 9 10 11 12 13].each { heap.add it }
    heap.combos { |x, y| a << "#{x};#{y}" }
    assert_equal 156, a.length
    assert_equal a, a.uniq
    assert_equal '13;12', a.first
    assert_equal '1;2', a.last
  end

  def test_add
    @heap.add(1)
    @heap.add(2)
    @heap.add(3)
    @heap.add(4)
    assert_equal [4, 3, 2], @heap.test_a
  end
end
# rubocop: enable Metrics
