#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'colorize'

# Mock Context for testing
# rubocop: disable Lint
class ContextMockup; end
# rubocop: enable Lint
class Error < RuntimeError; end
require 'korekto/handwaves'
module Korekto
  # Monkey patch for testing:
  class Handwaves
    attr_reader :handwaves, :captures

    def test_gsub!(pattern) = gsub!(pattern)
  end
end

class TestHandwaves < Test::Unit::TestCase
  # Trivial instantiating tests
  def test_new_push
    context = ContextMockup.new
    handwaves = Korekto::Handwaves.new(context)
    assert_equal handwaves.handwaves, []
    handwaves.push(':handwave-1')
    handwaves.push(':handwave-2')
    assert_equal handwaves.handwaves, [':handwave-1', ':handwave-2']
    # Attempt to push duplicate:
    e = assert_raises(Error) { handwaves.push(':handwave-2') }
    assert_equal e.message, 'duplicate handwave'
    # Does not start with ':':
    e = assert_raises(Error) { handwaves.push('handwave-3') }
    assert_equal e.message, 'unrecognized: handwave-3'
  end

  def test_check
    context = ContextMockup.new
    handwaves = Korekto::Handwaves.new(context)
    e = assert_raises(Error) { handwaves.check('statement') }
    assert_equal e.message, 'no handwaves found'
    # Don't do the following... :P
    handwaves.handwaves.push('bad handwave')
    # This is now a Runtime Error:
    e = assert_raises(RuntimeError) { handwaves.check('statement') }
    assert_equal e.message, 'unrecognized: bad handwave'
  end

  # TODO: Difficult to unit test.
  # Try to cover these paths with cucumber.
  # * ex_handwave?
  # * ex_step?
  # * statement_to_pattern
  # * ex_match_statement?
  # * ex_match_heap?
  # * ex_gsub_consequent?

  def test_gsub_bang
    context = ContextMockup.new
    handwaves = Korekto::Handwaves.new(context)
    handwaves.captures.push('A', 'B', 'C')
    pattern = String.new('$1 = $2 and $2 = $3, so $1 = $3')
    string = handwaves.test_gsub!(pattern)
    assert_equal string, 'A = B and B = C, so A = C'
  end

  # No fail warnings
  # rubocop: disable Metrics
  def test_instance_methods_coverage
    klass = Korekto::Handwaves
    methods = klass.instance_methods(false) +
              klass.private_instance_methods(false)
    methods.each do |method|
      test_method = "test_#{method}"
      test_method.sub!(/=$/, '_set')
      test_method.sub!(/!$/, '_bang')
      test_method.sub!(/\?$/, '_wut')
      next if respond_to? test_method.to_sym

      puts "Missing #{self.class}##{test_method}".red
    end
  end
  # rubocop: enable Metrics
end
