#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'test_module'
require 'korekto/heap'

# rubocop: disable Metrics
class TestHeap < Test::Unit::TestCase
  include TestModule

  def test_coverage = coverage Korekto::Heap

  def setup
    @heap = Korekto::Heap.new(3)
  end

  def test_private_constant_combos_for
    combos_for = Korekto::Heap.const_get(:COMBOS_FOR, false)
    # 3 combos where generated at the set up, but not 4:
    assert combos_for.key? 3
    refute combos_for.key? 4
    expected = @heap.instance_variable_get(:@combos)
    # It's the same array instance:
    assert_equal expected.object_id, combos_for[3].object_id
    # The array values are verified in `test_initialize`.
  end

  def test_initialize
    inspect = @heap.inspect
    # Three instance variables:
    assert_match(/\A#<Korekto::Heap:[^@]+@[^@]+@[^@]+@[^@]+\Z/, inspect)
    assert_match(/ @limit=3, /, inspect)
    assert_match(/ @heap=\[\], /, inspect)
    assert_match(/ @combos=\[\[0, /, inspect)
    expected = [[0, 1], [1, 0], [0, 2], [2, 0], [1, 2], [2, 1]]
    combos = @heap.instance_variable_get(:@combos)
    assert_equal expected, combos
  end

  def test_swap
    heap = @heap.instance_variable_get(:@heap)
    heap.push(1, 2, 3, 4)
    tmp = @heap.swap
    assert_equal [1, 2, 3, 4], tmp
    assert_empty @heap.instance_variable_get :@heap
    @heap.swap tmp
    assert_equal [1, 2, 3, 4], @heap.instance_variable_get(:@heap)
  end

  def test_follows
    heap = @heap.instance_variable_get(:@heap)
    heap.push(1, 2, 3, 4)
    assert_equal [2, 1], @heap.follows(1)
    assert_equal [3, 2, 1], @heap.follows(2)
  end

  def test_antecedent
    heap = @heap.instance_variable_get(:@heap)
    heap.push(1, 2, 3, 4)
    assert_equal '1', @heap.antecedent
  end

  def test_add
    @heap.add(1)
    @heap.add(2)
    @heap.add(3)
    @heap.add(4)
    assert_equal [4, 3, 2], @heap.instance_variable_get(:@heap)
  end

  def test_combos
    a = []

    @heap.combos { |s1, s2| a << "#{s1};#{s2}" }
    assert a.empty?

    @heap.add 'A'
    @heap.combos { |s1, s2| a << "#{s1};#{s2}" }
    assert a.empty?

    @heap.add 'B'
    @heap.combos { |s1, s2| a << "#{s1};#{s2}" }
    assert_equal 2, a.length
    assert_equal 'B;A', a[0]
    assert_equal 'A;B', a[1]

    a.clear
    @heap.add 'C'
    @heap.combos { |s1, s2| a << "#{s1};#{s2}" }
    assert_equal 6, a.length
    assert_equal 'C;B', a[0]
    assert_equal 'B;C', a[1]
    assert_equal 'C;A', a[2]
    assert_equal 'A;C', a[3]
    assert_equal 'B;A', a[4]
    assert_equal 'A;B', a[5]

    a.clear
    @heap.add 'D'
    @heap.combos { |s1, s2| a << "#{s1};#{s2}" }
    assert_equal 6, a.length
    # Note that with a heap of 3, "A" is gone.
    assert_equal 'D;C', a[0]
    assert_equal 'C;D', a[1]
    assert_equal 'D;B', a[2]
    assert_equal 'B;D', a[3]
    assert_equal 'C;B', a[4]
    assert_equal 'B;C', a[5]
  end

  def test_each
    # heap starts empty
    # rubocop: disable Lint/UnreachableLoop
    assert_nothing_raised { @heap.each { raise } }
    # rubocop: enable Lint/UnreachableLoop
    # heap iterates through a
    heap = @heap.instance_variable_get(:@heap)
    heap.push(1, 2, 3, 4)
    # map enabled by Enumerable via each
    assert_equal %w[1 2 3 4], @heap.map(&:to_s)
  end

  # Last, check rubocop and reek
  def test_rubocop_and_reek
    file = 'lib/korekto/heap.rb'
    rubocop(file) && reek(file)
  end
end
# rubocop: enable Metrics
