#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'colorize'
require 'korekto/handwaves'
require_relative 'test_module'

TEST_CLASS = Korekto::Handwaves

# Mockup
module Korekto
  class Error < RuntimeError; end

  class Statements
    attr_accessor :antecedent, :symbols, :heap
  end

  class Symbols
    def statement_to_pattern = nil
  end

  # Monkey patch for testing:
  class Handwaves
    def test_context = @context
    def test_handwaves = @handwaves
    def test_captures = @captures
    def test_gsub!(pattern) = gsub!(pattern)
  end
end

class TestHandwaves < Test::Unit::TestCase
  include TestModule

  def setup
    context = Korekto::Statements.new
    @handwaves = Korekto::Handwaves.new(context)
  end

  def test_initialize
    assert @handwaves.test_context.is_a? Korekto::Statements
    assert_equal [], @handwaves.test_handwaves
    assert_equal [], @handwaves.test_captures
  end

  def test_push
    @handwaves.push(':wut')
    assert_equal [':wut'], @handwaves.test_handwaves
    e = assert_raises(Korekto::Error) do
      @handwaves.push(':wut')
    end
    assert_equal 'duplicate handwave', e.message
    e = assert_raises(Korekto::Error) do
      @handwaves.push('wut')
    end
    assert_equal 'unrecognized handwave', e.message
  end

  def test_check_bang
    e = assert_raises(Korekto::Error) { @handwaves.check!('statement') }
    assert_equal e.message, 'no handwaves found'
    # Don't do the following... :P
    @handwaves.test_handwaves.push('bad handwave')
    # This is now a Runtime Error:
    e = assert_raises(RuntimeError) { @handwaves.check!('statement') }
    assert_equal e.message, 'unrecognized: bad handwave'
    # Monkey patch to isolate
    def @handwaves.ex_handwave?(*_args) = true
    @handwaves.test_handwaves.clear
    @handwaves.push(':something')
    assert_nil @handwaves.check!('Any now passes')
  end

  # TODO: Difficult to unit test.
  # Try to cover these paths with cucumber.
  # * ex_handwave?
  # * ex_step?
  # * statement_to_pattern
  # * ex_match_statement?
  # * ex_match_heap?
  # * ex_gsub_consequent?

  def test_gsub_bang
    context = Korekto::Statements.new
    handwaves = Korekto::Handwaves.new(context)
    handwaves.test_captures.push('A', 'B', 'C')
    pattern = String.new('$1 = $2 and $2 = $3, so $1 = $3')
    string = handwaves.test_gsub!(pattern)
    assert_equal string, 'A = B and B = C, so A = C'
  end
end
