#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'colorize'

class TestLongChains < Test::Unit::TestCase
  # Fail-less warnings
  def test_long_chains
    Dir.glob('lib/**/*.rb').each do |fn|
      `egrep '\\w+[.]\\w+[.]\\w+[.]\w+' #{fn}`.lines.map(&:strip).each do |line|
        puts "#{fn}: #{line.red}"
      end
    end
  end
end
