#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'colorize'
require 'korekto/main'
require_relative 'test_module'

class TestMain < Test::Unit::TestCase
  include TestModule

  def test_coverage = coverage Korekto::Main

  # Trivial instantiating tests
  def test_new
    main = Korekto::Main.new(statements: nil)
    assert main.respond_to? :run
  end
end
