#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'test_module'
require 'korekto/refinements'

class TestRefinements < Test::Unit::TestCase
  include TestModule

  using Korekto::Refinements

  def test_coverage = coverage(Korekto::Refinements)

  def test_string_balanced_wut
    assert '[This](is){balanced}'.balanced?
    assert '[T(h)is](is){ba[lanc]ed}'.balanced?
    refute 'This) (is not balanced'.balanced?
    refute 'This (is [not) ba]lanced'.balanced?
    assert '<This>is balanced'.balanced?('<>')
    refute 'This is>not<balanced'.balanced?('<>')
  end

  def test_string_ltight_wut
    assert 'Factorial: 2! = 4'.ltight?('!')
    assert 'Factorial: 2! = 4'.ltight?(':')
    refute 'Factorial: 2! = 4'.ltight?('2')
    refute 'Factorial: 2! = 4'.ltight?('=')
    assert 'Factorial: 2! = 4'.ltight?('o')
  end

  def test_string_rtight_wut
    refute 'Factorial: 2! = 4'.rtight?('!')
    refute 'Factorial: 2! = 4'.rtight?(':')
    assert 'Factorial: 2! = 4'.rtight?('2')
    refute 'Factorial: 2! = 4'.rtight?('=')
    assert 'Factorial: 2! = 4'.rtight?('o')
  end

  def test_string_tight_wut
    refute 'Factorial: 2! = 4'.tight?('!')
    refute 'Factorial: 2! = 4'.tight?(':')
    refute 'Factorial: 2! = 4'.tight?('2')
    refute 'Factorial: 2! = 4'.tight?('=')
    assert 'Factorial: 2! = 4'.tight?('o')
  end

  def test_string_gsub_tokens_bang
    string = String.new '$1$2$3: $4 = $5'
    string.gsub_tokens!(['Fac', 'to', 'rial', '2!', '4'])
    assert_equal 'Factorial: 2! = 4', string
    string = String.new '$2, $12, $1, $11, $10, $1$2'
    tokens = %w[One Two Three Four Five Six Seven Eight Nine Ten Eleven Twelve]
    string.gsub_tokens!(tokens)
    assert_equal 'Two, Twelve, One, Eleven, Ten, OneTwo', string
  end

  def test_string_match_to_i
    assert_equal 123, 'Wut 123 is?'.match_to_i(/\d+/)
  end

  def test_string_wrapped_by_wut
    assert_equal true, 'awuta'.wrapped_by?('a')
    assert_equal false, 'awutb'.wrapped_by?('a')
    assert_equal true, 'bb'.wrapped_by?('b')
    assert_equal false, 'c'.wrapped_by?('c')
    assert_equal false, ''.wrapped_by?('x')
  end

  # Last, check rubocop and reek
  def test_rubocop_and_reek
    file = 'lib/korekto/refinements.rb'
    rubocop(file) && reek(file) && rubocop(__FILE__)
  end
end
