#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'test_module'
require 'korekto/refinements'

class TestRefinements < Test::Unit::TestCase
  include TestModule

  using Korekto::Refinements

  def test_coverage = coverage(Korekto::Refinements)

  def test_string_balanced_wut
    assert '[This](is){balanced}'.balanced?
    assert '[T(h)is](is){ba[lanc]ed}'.balanced?
    refute 'This) (is not balanced'.balanced?
    refute 'This (is [not) ba]lanced'.balanced?
    assert '<This>is balanced'.balanced?('<>')
    refute 'This is>not<balanced'.balanced?('<>')
  end

  def test_string_ltight_wut
    assert 'Factorial: 2! = 4'.ltight?('!')
    assert 'Fatorial: 2! = 4'.ltight?(':')
    refute 'Fatorial: 2! = 4'.ltight?('2')
    refute 'Fatorial: 2! = 4'.ltight?('=')
    assert 'Fatorial: 2! = 4'.ltight?('o')
  end

  def test_string_rtight_wut
    refute 'Factorial: 2! = 4'.rtight?('!')
    refute 'Fatorial: 2! = 4'.rtight?(':')
    assert 'Fatorial: 2! = 4'.rtight?('2')
    refute 'Fatorial: 2! = 4'.rtight?('=')
    assert 'Fatorial: 2! = 4'.rtight?('o')
  end

  def test_string_tight_wut
    refute 'Factorial: 2! = 4'.tight?('!')
    refute 'Fatorial: 2! = 4'.tight?(':')
    refute 'Fatorial: 2! = 4'.tight?('2')
    refute 'Fatorial: 2! = 4'.tight?('=')
    assert 'Fatorial: 2! = 4'.tight?('o')
  end
end
