#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'korekto/refinements'

class TestRefinements < Test::Unit::TestCase
  using Korekto::Refinements

  def test_balanced_true
    assert '[This](is){balanced}'.balanced?
    assert '[T(h)is](is){ba[lanc]ed}'.balanced?
  end

  def test_balanced_false
    refute 'This) (is not balanced'.balanced?
    refute 'This (is [not) ba]lanced'.balanced?
  end

  def test_balanced_other
    assert '<This>is balanced'.balanced?('<>')
    refute 'This is>not<balanced'.balanced?('<>')
  end

  def test_ltight
    assert 'Factorial: 2! = 4'.ltight?('!')
    assert 'Fatorial: 2! = 4'.ltight?(':')
    refute 'Fatorial: 2! = 4'.ltight?('2')
    refute 'Fatorial: 2! = 4'.ltight?('=')
    assert 'Fatorial: 2! = 4'.ltight?('o')
  end

  def test_rtight
    refute 'Factorial: 2! = 4'.rtight?('!')
    refute 'Fatorial: 2! = 4'.rtight?(':')
    assert 'Fatorial: 2! = 4'.rtight?('2')
    refute 'Fatorial: 2! = 4'.rtight?('=')
    assert 'Fatorial: 2! = 4'.rtight?('o')
  end

  def test_tight
    refute 'Factorial: 2! = 4'.tight?('!')
    refute 'Fatorial: 2! = 4'.tight?(':')
    refute 'Fatorial: 2! = 4'.tight?('2')
    refute 'Fatorial: 2! = 4'.tight?('=')
    assert 'Fatorial: 2! = 4'.tight?('o')
  end
end
