#!/usr/bin/env ruby
require 'test/unit'
module Korekto
  class Error < RuntimeError; end
end
require 'korekto/refinements'
require 'korekto/rules'

class TestSymbols < Test::Unit::TestCase
  def test_sytax
    rules = Korekto::Rules.new
    rules.push 'length < 120'
    assert_equal ['length < 120'], rules.to_a
    error = assert_raises(Korekto::Error) do
      rules.push 'length'
    end
    assert_equal 'rules must eval boolean', error.message
    error = assert_raises(Korekto::Error) do
      rules.push 'leNgTh < 120'
    end
    assert_equal 'NameError: leNgTh < 120', error.message
    rules.push 'is_a? String'
    assert_nil rules.detect('ABC', false)
  end
end
