#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'colorize'
require 'korekto/statements'
require_relative 'test_module'

class TestStatements < Test::Unit::TestCase
  include TestModule

  def test_coverage = coverage Korekto::Statements
end
