#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'colorize'
require_relative 'test_module'
require 'korekto/refinements'
require 'korekto/syntax'
# Mockups
module Korekto
  class Error < RuntimeError; end

  class Syntax
    def test_syntax = @syntax
  end
end

TEST_CLASS = Korekto::Syntax

class TestSyntax < Test::Unit::TestCase
  include TestModule

  def setup
    @syntax = Korekto::Syntax.new
  end

  def test_initialize
    assert_equal [], @syntax.test_syntax
  end

  # rubocop: disable Metrics
  def test_push
    @syntax.push 'length < 120'
    assert_equal ['length < 120'], @syntax.test_syntax
    error = assert_raises(Korekto::Error) do
      @syntax.push 'length'
    end
    assert_equal 'syntax must eval boolean', error.message
    error = assert_raises(Korekto::Error) do
      @syntax.push 'leNgTh < 120'
    end
    assert_equal 'NameError: leNgTh < 120', error.message
    error = assert_raises(Korekto::Error) do
      @syntax.push 'length < 120'
    end
    assert_equal 'duplicate syntax', error.message
    @syntax.push "ltight?('!')"
    assert_equal ['length < 120', "ltight?('!')"], @syntax.test_syntax
  end

  def test_check
    @syntax.push "ltight?('!')"
    assert_nothing_raised do
      @syntax.check('2! = 4')
    end
    error = assert_raises(Korekto::Error) do
      @syntax.check('2 ! = 4')
    end
    assert_equal "syntax: ltight?('!')", error.message
  end
  # rubocop: enable Metrics
end
