#!/usr/bin/env ruby
# frozen_string_literal: true

CMD = ARGV.shift
list = *ARGV
list = `tmux list-panes -F '#P'`.split if list.empty?
list.each do |i|
  running = `tmux display -t ":.#{i}" -p '\#{pane_current_command}'`.chomp
  cmd = CMD || "pane #{i}"
  `tmux send-keys -t ":.#{i}" "#{cmd}" Enter` if running == 'fish'
end
